# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 406634b54124b92d65dd33c9ed7574e7eea074ef98b8e2d6230243275d56b3b0b592b694fe011c301a7c8b4dc3a8794a37841b2635f1610a1af2e02363a997cc

test:
  secret_key_base: fdb043bafa7314f28544644e15b5e4a18bcd6d4137640c84ab8549b1f4653428d3c64526a813d703a4b3e18f8293568fc20ba0106c661891fe0b49254db6e63b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
